# Generated by Django 3.2 on 2021-05-07 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agronomist_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agronomist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.agronomist')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.location')),
            ],
        ),
    ]
