# Generated by Django 3.2 on 2021-05-08 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_agronomist_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence_Agr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curr_latitude', models.FloatField(default=0.0)),
                ('curr_longitude', models.FloatField(default=0.0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('agronomist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.agronomist')),
            ],
        ),
    ]
