# Generated by Django 3.2 on 2021-06-14 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0005_attendence_agr_attendance_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence_agr',
            name='curr_latitude',
        ),
        migrations.RemoveField(
            model_name='attendence_agr',
            name='curr_longitude',
        ),
    ]
