# Generated by Django 3.2 on 2021-06-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0006_auto_20210614_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='agronomist',
            name='agr_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
